export type EmployeeDetail = {
  code: string;
  name: string;
  role: string;
  branch: string;
  status: string;
  workType: string;
  phone: string;
  email: string;
  joinDate: string;
  salary: string;
  kpiSalary: string;
  gender: string;
  birthday: string;
  currentAddress: string;
  permanentAddress: string;
  bankAccount: string;
  emergencyPhone: string;
  ethnicity: string;
  idNumber: string;
  idIssueDate: string;
  department: string;
  level: string;
  payrollMethod: string;
  insuranceStatus: string;
  insuranceSalary: string;
  dependentCount: string;
  taxCode: string;
  taxIssueDate: string;
  taxAddress: string;
  attendanceEnabled: string;
  payrollEnabled: string;
  smartphoneAttendance: string;
  attendanceDevice: string;
  faceAttendance: string;
};

export const employees: EmployeeDetail[] = [
  {
    code: "NV001",
    name: "Nguyen Minh Chau",
    role: "Store manager",
    branch: "Central store",
    status: "Working",
    workType: "Full time",
    phone: "0901 223 456",
    email: "chau.nguyen@kltn.vn",
    joinDate: "16/03/2026",
    salary: "20,000,000 VND",
    kpiSalary: "2,500,000 VND",
    gender: "Female",
    birthday: "14/02/1997",
    currentAddress: "Cau Giay, Ha Noi",
    permanentAddress: "Nam Dinh",
    bankAccount: "VCB - 1029384756",
    emergencyPhone: "0988 123 456",
    ethnicity: "Kinh",
    idNumber: "001197000123",
    idIssueDate: "20/08/2021",
    department: "Operations",
    level: "Team lead",
    payrollMethod: "By branch attendance",
    insuranceStatus: "Yes",
    insuranceSalary: "12,000,000 VND",
    dependentCount: "0",
    taxCode: "0109988776",
    taxIssueDate: "18/03/2026",
    taxAddress: "Ha Noi",
    attendanceEnabled: "Yes",
    payrollEnabled: "Yes",
    smartphoneAttendance: "Yes",
    attendanceDevice: "Flexible attendance on all devices",
    faceAttendance: "Not enabled",
  },
  {
    code: "NV002",
    name: "Tran Bao Ngan",
    role: "Cashier",
    branch: "Central store",
    status: "Working",
    workType: "Full time",
    phone: "0908 567 112",
    email: "ngan.tran@kltn.vn",
    joinDate: "11/03/2026",
    salary: "11,500,000 VND",
    kpiSalary: "800,000 VND",
    gender: "Female",
    birthday: "02/06/1998",
    currentAddress: "Thanh Xuan, Ha Noi",
    permanentAddress: "Hai Duong",
    bankAccount: "MB - 2345678910",
    emergencyPhone: "0977 223 991",
    ethnicity: "Kinh",
    idNumber: "001198002222",
    idIssueDate: "12/05/2020",
    department: "Cashier",
    level: "Staff",
    payrollMethod: "By branch attendance",
    insuranceStatus: "No",
    insuranceSalary: "-",
    dependentCount: "0",
    taxCode: "-",
    taxIssueDate: "-",
    taxAddress: "-",
    attendanceEnabled: "Yes",
    payrollEnabled: "Yes",
    smartphoneAttendance: "Yes",
    attendanceDevice: "Store attendance machine",
    faceAttendance: "Yes",
  },
  {
    code: "NV003",
    name: "Pham Quoc Huy",
    role: "Sales staff",
    branch: "Online warehouse",
    status: "On leave",
    workType: "Night shift",
    phone: "0912 450 888",
    email: "huy.pham@kltn.vn",
    joinDate: "20/02/2026",
    salary: "9,000,000 VND",
    kpiSalary: "500,000 VND",
    gender: "Male",
    birthday: "10/10/2000",
    currentAddress: "Long Bien, Ha Noi",
    permanentAddress: "Thai Binh",
    bankAccount: "-",
    emergencyPhone: "0912 000 999",
    ethnicity: "Kinh",
    idNumber: "-",
    idIssueDate: "-",
    department: "Sales",
    level: "Staff",
    payrollMethod: "By branch attendance",
    insuranceStatus: "No",
    insuranceSalary: "-",
    dependentCount: "0",
    taxCode: "-",
    taxIssueDate: "-",
    taxAddress: "-",
    attendanceEnabled: "Yes",
    payrollEnabled: "Yes",
    smartphoneAttendance: "No",
    attendanceDevice: "Warehouse attendance machine",
    faceAttendance: "No",
  },
  {
    code: "NV004",
    name: "Le Thao Vy",
    role: "Warehouse specialist",
    branch: "Main warehouse",
    status: "Working",
    workType: "Full time",
    phone: "0933 218 045",
    email: "vy.le@kltn.vn",
    joinDate: "05/01/2026",
    salary: "12,800,000 VND",
    kpiSalary: "1,200,000 VND",
    gender: "Female",
    birthday: "09/09/1996",
    currentAddress: "Hoang Mai, Ha Noi",
    permanentAddress: "Bac Ninh",
    bankAccount: "Techcombank - 3344556677",
    emergencyPhone: "0933 777 111",
    ethnicity: "Kinh",
    idNumber: "001196009999",
    idIssueDate: "01/11/2021",
    department: "Warehouse",
    level: "Senior staff",
    payrollMethod: "By branch attendance",
    insuranceStatus: "Yes",
    insuranceSalary: "10,000,000 VND",
    dependentCount: "1",
    taxCode: "0105566778",
    taxIssueDate: "06/01/2026",
    taxAddress: "Ha Noi",
    attendanceEnabled: "Yes",
    payrollEnabled: "Yes",
    smartphoneAttendance: "Yes",
    attendanceDevice: "Fingerprint machine",
    faceAttendance: "No",
  },
  {
    code: "NV005",
    name: "Doan Gia Han",
    role: "Customer care",
    branch: "Central store",
    status: "Working",
    workType: "Part time",
    phone: "0987 654 321",
    email: "han.doan@kltn.vn",
    joinDate: "28/02/2026",
    salary: "7,500,000 VND",
    kpiSalary: "400,000 VND",
    gender: "Female",
    birthday: "19/04/2001",
    currentAddress: "Dong Da, Ha Noi",
    permanentAddress: "Ha Nam",
    bankAccount: "-",
    emergencyPhone: "0987 999 222",
    ethnicity: "Kinh",
    idNumber: "-",
    idIssueDate: "-",
    department: "Customer care",
    level: "Staff",
    payrollMethod: "By branch attendance",
    insuranceStatus: "No",
    insuranceSalary: "-",
    dependentCount: "0",
    taxCode: "-",
    taxIssueDate: "-",
    taxAddress: "-",
    attendanceEnabled: "Yes",
    payrollEnabled: "Yes",
    smartphoneAttendance: "Yes",
    attendanceDevice: "Mobile attendance",
    faceAttendance: "No",
  },
  {
    code: "NV006",
    name: "Vo Duc Long",
    role: "Sales staff",
    branch: "Ha Dong branch",
    status: "Probation",
    workType: "Morning shift",
    phone: "0966 887 120",
    email: "long.vo@kltn.vn",
    joinDate: "15/03/2026",
    salary: "8,200,000 VND",
    kpiSalary: "300,000 VND",
    gender: "Male",
    birthday: "11/11/2002",
    currentAddress: "Ha Dong, Ha Noi",
    permanentAddress: "Thanh Hoa",
    bankAccount: "-",
    emergencyPhone: "0966 000 555",
    ethnicity: "Kinh",
    idNumber: "-",
    idIssueDate: "-",
    department: "Sales",
    level: "Probation",
    payrollMethod: "By branch attendance",
    insuranceStatus: "No",
    insuranceSalary: "-",
    dependentCount: "0",
    taxCode: "-",
    taxIssueDate: "-",
    taxAddress: "-",
    attendanceEnabled: "Yes",
    payrollEnabled: "Yes",
    smartphoneAttendance: "Yes",
    attendanceDevice: "Mobile attendance",
    faceAttendance: "No",
  },
  {
    code: "NV007",
    name: "Bui Khanh Linh",
    role: "Cashier",
    branch: "Ha Dong branch",
    status: "Working",
    workType: "Morning shift",
    phone: "0944 778 223",
    email: "linh.bui@kltn.vn",
    joinDate: "08/03/2026",
    salary: "10,300,000 VND",
    kpiSalary: "700,000 VND",
    gender: "Female",
    birthday: "23/05/1999",
    currentAddress: "Ha Dong, Ha Noi",
    permanentAddress: "Ninh Binh",
    bankAccount: "ACB - 6677889900",
    emergencyPhone: "0944 000 888",
    ethnicity: "Kinh",
    idNumber: "001199004444",
    idIssueDate: "22/07/2022",
    department: "Cashier",
    level: "Staff",
    payrollMethod: "By branch attendance",
    insuranceStatus: "Yes",
    insuranceSalary: "8,000,000 VND",
    dependentCount: "0",
    taxCode: "0107654321",
    taxIssueDate: "10/03/2026",
    taxAddress: "Ha Noi",
    attendanceEnabled: "Yes",
    payrollEnabled: "Yes",
    smartphoneAttendance: "Yes",
    attendanceDevice: "Store attendance machine",
    faceAttendance: "Yes",
  },
  {
    code: "NV008",
    name: "Dang Tuan Kiet",
    role: "Warehouse specialist",
    branch: "Main warehouse",
    status: "Working",
    workType: "Night shift",
    phone: "0971 336 889",
    email: "kiet.dang@kltn.vn",
    joinDate: "03/02/2026",
    salary: "11,000,000 VND",
    kpiSalary: "600,000 VND",
    gender: "Male",
    birthday: "30/08/1998",
    currentAddress: "Gia Lam, Ha Noi",
    permanentAddress: "Hung Yen",
    bankAccount: "VPBank - 7711223344",
    emergencyPhone: "0971 444 555",
    ethnicity: "Kinh",
    idNumber: "001198007777",
    idIssueDate: "09/12/2020",
    department: "Warehouse",
    level: "Senior staff",
    payrollMethod: "By branch attendance",
    insuranceStatus: "Yes",
    insuranceSalary: "9,500,000 VND",
    dependentCount: "2",
    taxCode: "0101239876",
    taxIssueDate: "04/02/2026",
    taxAddress: "Ha Noi",
    attendanceEnabled: "Yes",
    payrollEnabled: "Yes",
    smartphoneAttendance: "No",
    attendanceDevice: "Fingerprint machine",
    faceAttendance: "No",
  },
];

export const roleOptions = ["All roles", "Store manager", "Cashier", "Sales staff", "Warehouse specialist", "Customer care"];
export const branchOptions = ["All branches", "Central store", "Main warehouse", "Online warehouse", "Ha Dong branch"];
export const statusOptions = ["All status", "Working", "Probation", "On leave"];
export const workTypeOptions = ["All shifts", "Full time", "Part time", "Morning shift", "Night shift"];
